### ISSUE TITLE
Missing selection-mode property on People Picker

### ISSUE THREAD

**Issue by cmw2** [nmetulev/mgt-react#1]
The base mgt-people-picker component has a selection-mode property that doesn't seem to exist in the wrapper.  Can we get that added to the wrapper?

**Comment by nmetulev** [comment]
Hey @cmw2, I've recently started building mgt-react directly in the mgt repo and published new packages under the @micorosft/mgt-react name which should have all the properties. I will go ahead and archive this repo and update the readme to point to the new package.

**Comment by nmetulev** [comment]
Here is the updated link: https://www.npmjs.com/package/@microsoft/mgt-react
